# Generated by Django 4.1.3 on 2023-11-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='czy_wylosowany',
            field=models.BooleanField(default=False),
        ),
    ]
